### ISSUE TITLE
Fix errors in console

### ISSUE THREAD

**Issue by HampusAndersson01** [HampusAndersson01/Parameter-Database#121]

**Comment by HampusAndersson01** [comment]
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ParameterTable`. See https://reactjs.org/link/warning-keys for more information.
    at ParameterTable (http://localhost:3001/static/js/main.chunk.js:1864:77)
    at div
    at App (http://localhost:3001/static/js/main.chunk.js:251:73)
``` 
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `StyledBoxWLabel`. See https://reactjs.org/link/warning-keys for more information.
    at input
    at StyledBoxWLabel (http://localhost:3001/static/js/main.chunk.js:2385:77)
    at div
    at div
    at td
    at tr
    at ExpandedData (http://localhost:3001/static/js/main.chunk.js:629:73)
    at tbody
    at table
    at div
    at ParameterTable (http://localhost:3001/static/js/main.chunk.js:1864:77)
    at div
    at App (http://localhost:3001/static/js/main.chunk.js:251:73)
``` 
```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
    at input
    at fieldset
    at div
    at StyledBoxWLabel (http://localhost:3001/static/js/main.chunk.js:2385:77)
    at div
    at div
    at td
    at tr
    at ExpandedData (http://localhost:3001/static/js/main.chunk.js:629:73)
    at tbody
    at table
    at div
    at ParameterTable (http://localhost:3001/static/js/main.chunk.js:1864:77)
    at div
    at App (http://localhost:3001/static/js/main.chunk.js:251:73)
``` 
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at fieldset
    at div
    at StyledBoxWLabel (http://localhost:3001/static/js/main.chunk.js:2385:77)
    at div
    at div
    at td
    at tr
    at ExpandedData (http://localhost:3001/static/js/main.chunk.js:629:73)
    at tbody
    at table
    at div
    at ParameterTable (http://localhost:3001/static/js/main.chunk.js:1864:77)
    at div
    at App (http://localhost:3001/static/js/main.chunk.js:251:73)
```
